version: '3'

volumes:
  mongo:
    external: true

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db:cached
    logging: *default-logging
